apply plugin: 'io.osrsx.plugin'

osrsxPlugin {
    id = 'cooker'
    group = 'io.osrsx.plugins'
    version = '1.1.0'
    name = 'Cooker'
    description = 'Cooks raw food at a range or fire.'
    authors = ['osrsx']
    tags = ['skilling', 'cooking', 'processing']
    requires 'skilling-lib:1.0.0'
}
